Revert "[APS] Skip installing apps which are already OEM installed"
This reverts commit f37583a1e9426c517401bcc4d29597b1c7029543.

Reason for revert: Conflicts with CL:4078650
It moved the newly introduced include:

FAILED: obj/chrome/test/unit_tests/app_preload_service_unittest.o
../../buildtools/reclient/rewrapper -cfg=../../buildtools/reclient_cfgs/chromium-browser-clang/rewra...(too long)
../../chrome/browser/apps/app_preload_service/app_preload_service_unittest.cc:21:10: fatal error: 'chrome/browser/ui/app_list/arc/arc_app_list_prefs.h' file not found
#include "chrome/browser/ui/app_list/arc/arc_app_list_prefs.h"

Please resubmit with adapted include path.

Original change's description:
> [APS] Skip installing apps which are already OEM installed
>
> If there are any errors while installing apps through App Preload
> Service, we will retry the entire installation flow on next startup. To
> avoid additional work, we will now filter out apps which were
> successfully installed already and only install missing apps.
>
> Additionally, this adds a filter to avoid installing 'default' apps,
> which are not supported by the APS client yet.
>
> Bug: b/259152331
> Change-Id: Ib7b15b4f2271f69c10883f38383e4980bb54b6bc
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4080287
> Auto-Submit: Tim Sergeant <tsergeant@chromium.org>
> Reviewed-by: Jeevan Shikaram <jshikaram@chromium.org>
> Commit-Queue: Tim Sergeant <tsergeant@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1079681}

Bug: b/259152331
Change-Id: Id4dc72be3d9126838f14243a56c9e0e75b1fe221
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4079158
Commit-Queue: Michael Ershov <miersh@google.com>
Commit-Queue: Irem Uguz <iremuguz@google.com>
Owners-Override: Pavol Marko <pmarko@chromium.org>
Reviewed-by: Irem Uguz <iremuguz@google.com>
Auto-Submit: Pavol Marko <pmarko@chromium.org>
Reviewed-by: Michael Ershov <miersh@google.com>
Cr-Commit-Position: refs/heads/main@{#1079686}