Revert "IOSurfaceImageBacking: Do not allocate GLImage for anonymous images"
This reverts commit 3150c81fd73f1c89f26f1d7f302b4f42307f6d57.

Reason for revert: Suspecting culprit for compile failure.

[1121/2444] CXX obj/gpu/command_buffer/service/gles2_sources/shared_image_factory.o
FAILED: obj/gpu/command_buffer/service/gles2_sources/shared_image_factory.o
../../buildtools/reclient/rewrapper -cfg=../../buildtools/reclient_cfgs/chromium-browser-clang/rewra...(too long)
In file included from ../../gpu/command_buffer/service/shared_image/shared_image_factory.cc:24:
../../gpu/command_buffer/service/shared_image/iosurface_image_backing_factory.h:45:12: error: no type named 'ScopedIOSurface' in namespace 'gfx'
gfx::ScopedIOSurface io_surface,
~~~~~^
../../gpu/command_buffer/service/shared_image/iosurface_image_backing_factory.h:52:12: error: no type named 'ScopedIOSurface' in namespace 'gfx'

Original change's description:
> IOSurfaceImageBacking: Do not allocate GLImage for anonymous images
>
> Change IOSurfaceImageBacking to no longer go through the
> GLImageIOSurface to get a the IOSurface and related parameters.
>
> Change IOSurfaceImageBackingFactory::CreateSharedImageInternal to no
> longer allocate a GLImage.
>
> Do not yet update the IOSurfaceImageBackingFactory::CreateSharedImage
> which take a GpuMemoryBufferHandle to do this yet (it has several
> other interactions that need to be cleaned up separately).
>
> Change-Id: Ic840bcb5f9a3b7f213e2a026476683c1566b32a4
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4061651
> Commit-Queue: ccameron chromium <ccameron@chromium.org>
> Reviewed-by: Vasiliy Telezhnikov <vasilyt@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1076752}

Change-Id: Iecfd43a47d58bed78c0f7bdcff70191db86407f0
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4061847
Owners-Override: Balazs Engedy <engedy@chromium.org>
Commit-Queue: Balazs Engedy <engedy@chromium.org>
Reviewed-by: Balazs Engedy <engedy@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1076755}