Revert "[bookmarks] Move testing code to bookmarks directory"
This reverts commit 12deed6c5a8f9220b15fcaf995cf7c5ba7873233.

Reason for revert: http://crbug.com/1395371

Broke downstream bots like:
PartnerBookmarksIntegrationTest.java:29: error: cannot find symbol
import org.chromium.chrome.test.util.BookmarkTestUtil;
                                    ^
symbol:   class BookmarkTestUtil

Original change's description:
> [bookmarks] Move testing code to bookmarks directory
>
> Change-Id: Iafc8cf64de55a3385d73611e73c20362622a7aa1
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4071045
> Commit-Queue: Theresa Sullivan <twellington@chromium.org>
> Reviewed-by: Theresa Sullivan <twellington@chromium.org>
> Auto-Submit: Brandon Wylie <wylieb@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1078384}

Change-Id: Ife315802690b56191056bd8d259b93eac3f8421b
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4076127
Commit-Queue: Egor Pasko <pasko@chromium.org>
Reviewed-by: Boris Sazonov <bsazonov@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Egor Pasko <pasko@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1078601}