fixup! ozone/wayland: check format support for overlays candidate
This fixes the following build error, introduced by [1] when
`use_wayland_gbm` is false in GN args.

> ../../ui/o/p/w/g/wayland_overlay_manager_unittest.cc:7:10:
>               fatal error: 'drm_fourcc.h' file not found
> #include <drm_fourcc.h>
>          ^~~~~~~~~~~~~~

[1] https://crrev.com/c/4023324

BUG=none
R=msisov@igalia.com

Change-Id: Icdbd96d201d34f88f16e0fba842b90afc1c032d4
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4041708
Commit-Queue: Maksim Sisov <msisov@igalia.com>
Auto-Submit: Antonio Gomes <tonikitoo@igalia.com>
Reviewed-by: Maksim Sisov <msisov@igalia.com>
Cr-Commit-Position: refs/heads/main@{#1073930}