Revert "Removed Platform Provided Trust Tokens"
This reverts commit f4be8032e0cefdfe9dfbf5c8c179faede19add35.

Reason for revert: Compile failure broke the tree:
https://ci.chromium.org/ui/p/chromium/builders/ci/linux-archive-rel/81290/overview

[91033/97417] CXX obj/content/test/content_browsertests/trust_token_browsertest.o
FAILED: obj/content/test/content_browsertests/trust_token_browsertest.o
../../buildtools/reclient/rewrapper -cfg=../../buildtools/reclient_cfgs/chromium-browser-clang/rewra...(too long)
In file included from ../../content/browser/network/trust_token_browsertest.cc:5:
../../content/browser/network/trust_token_browsertest.h:11:10: fatal error: 'content/public/common/trust_tokens.mojom.h' file not found
#include "content/public/common/trust_tokens.mojom.h"
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[91097/97417] CXX obj/content/test/content_browsertests/devtools_trust_token_browsertest.o

Original change's description:
> Removed Platform Provided Trust Tokens
>
> As we don't currently plan to release platform provided trust tokens, this CL removes
> the existing code implementing them.
>
> Fixed: 1395146
>
> Change-Id: I71b395fad7ef4242c70c9cf281e02ecdc2234f76
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4052381
> Reviewed-by: Yaron Friedman <yfriedman@chromium.org>
> Reviewed-by: Yang Guo <yangguo@chromium.org>
> Reviewed-by: danakj <danakj@chromium.org>
> Reviewed-by: Richard Coles <torne@chromium.org>
> Reviewed-by: Daniel Murphy <dmurph@chromium.org>
> Reviewed-by: David Schinazi <dschinazi@chromium.org>
> Reviewed-by: Steven Valdez <svaldez@chromium.org>
> Reviewed-by: John Abd-El-Malek <jam@chromium.org>
> Commit-Queue: Sam Schlesinger <samschlesinger@google.com>
> Reviewed-by: Max Curran <curranmax@chromium.org>
> Reviewed-by: Simon Zünd <szuend@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1080199}

Bug: 1395146
Change-Id: I8f8377620e4563faef9bc83e9a1c8b6b01a09e33
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4082472
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Johann Koenig <johannkoenig@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Johann Koenig <johannkoenig@google.com>
Cr-Commit-Position: refs/heads/main@{#1080207}