externs: remove webview_tag from generated list
This API doesn't compile, so remove from the list to trigger automatic
generation until that's resolved.

$ tools/json_schema_compiler/compiler.py \
    chrome/common/extensions/api/webview_tag.json \
    --root=. --generator=externs
Traceback (most recent call last):
  File ".../tools/json_schema_compiler/compiler.py", line 211, in <module>
    result = GenerateSchema(opts.generator, file_paths, opts.root, opts.destdir,
  File ".../tools/json_schema_compiler/compiler.py", line 77, in GenerateSchema
    namespace = api_model.AddNamespace(target_namespace,
  File ".../tools/json_schema_compiler/model.py", line 49, in AddNamespace
    namespace = Namespace(json,
  File ".../tools/json_schema_compiler/model.py", line 148, in __init__
    self.functions = _GetFunctions(self, json, self)
  File ".../tools/json_schema_compiler/model.py", line 815, in _GetFunctions
    function = Function(parent,
  File ".../tools/json_schema_compiler/model.py", line 412, in __init__
    self.params.append(GeneratePropertyFromParam(param))
  File ".../tools/json_schema_compiler/model.py", line 372, in GeneratePropertyFromParam
    return Property(self, p['name'], p, namespace, origin)
  File ".../tools/json_schema_compiler/model.py", line 525, in __init__
    self.type_ = Type(parent, name, json, namespace, origin)
  File ".../tools/json_schema_compiler/model.py", line 255, in __init__
    raise ParseException(
model.ParseException: Model parse exception at:
webviewTag
stopFinding
action
  in chrome/common/extensions/api/webview_tag.json
Inline enum "action" found in namespace "webviewTag". These are not allowed. See crbug.com/472279

Bug: 469920
Change-Id: I95788a4d2c89902a4d6f2a0c7ed7ddd666326bd7
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4067065
Reviewed-by: David Bertoni <dbertoni@chromium.org>
Auto-Submit: Mike Frysinger <vapier@chromium.org>
Commit-Queue: David Bertoni <dbertoni@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1079286}