Set the path to MSVC when running x.py to build Rust.
This allows linking to work, now we fail because x.py is passing
invalid arguments to the LLVM archiver.

```
error: failed to run custom build command for `lzma-sys v0.1.17`
```

We set the archiver in the environment:

AR = Some("C:\\b\\s\\w\\ir\\cache\\builder\\src\\third_party\\llvm-build\\Release+Asserts\\bin\\llvm-ar")

The command that fails is:

```
"C:\\b\\s\\w\\ir\\cache\\builder\\src\\third_party\\llvm-build\\Release+Asserts\\bin\\llvm-ar" "-out:C:\\b\\s\\w\\ir\\cache\\builder\\src\\third_party\\rust_src\\src\\build\\bootstrap\\debug\\build\\lzma-sys-b4fbaf154720cb7c\\out\\liblzma.a" "-nologo" ...lots of .o files...
```

It seems that the -nologo argument is the problem.

Bug: 1271215
Change-Id: I03636eee44a22b92c63ee4beb43711ffb766c95b
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4087043
Commit-Queue: danakj <danakj@chromium.org>
Reviewed-by: Hans Wennborg <hans@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1081462}